seed: 1234
cuda_device: 0
batch_size: 1
text_column_name: tokens
label_column_name: ner_tags
scenario:
  name: few_shot_linear_readout
  metrics:
    - accuracy
    - f1_micro
    - f1_macro

defaults:
  - dataset: conll2003
  - dataset_processor: albert
  - encoder: albert
  - evaluation/dataset: nway_kshot_5_10
  - evaluation/classifier: nearest_centroid
