# @package dataset_processor

_target_: fewie.dataset_processors.transformer.TransformerProcessor
tokenizer_name_or_path: vblagoje/bert-english-uncased-finetuned-pos 
max_length: 128
label_all_tokens: false
